#Cran packages ----
install.packages("devtools")
install.packages("plotly")
install.packages("zip")
install.packages("filesstrings")
install.packages("shinydashboard")
install.packages("shinycustomloader")
install.packages("dashboardthemes")
install.packages("doParallel")
install.packages("MUVR")
install.packages("DT")
install.packages("mixOmics")
install.packages("shinyalert")
install.packages("httr")
install.packages("curl")
install.packages("RCurl")
install.packages("XML")
install.packages("RJSONIO")
install.packages("sqldf")
install.packages("igraph")
install.packages("S4Vectors")
install.packages("methods")
install.packages("xml2")
install.packages("png")
install.packages("fs")
install.packages("zoom")
install.packages("htmlwidgets")
install.packages("graph")
install.packages("jsonlite")
install.packages("R.utils")
install.packages("igraph")
install.packages("shinycustomloader")
install.packages("shinydashboard")
install.packages("shinyBS")

#Github packages ----
devtools::install_github('cytoscape/cyjShiny')
devtools::install_github('mrjoh3/cytoscape')
detach("package:InterMineR", unload = TRUE)
devtools::install_github('intermine/InterMineR')

#Bioconductor packages ----
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Biostrings")
BiocManager::install("RCyjs")
BiocManager::install("RCy3")
