#Cran packages ----
install.packages("devtools")
install.packages("plotly")
install.packages("zip")
install.packages("filesstrings")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinycustomloader")
install.packages("dashboardthemes")
install.packages("doParallel")
install.packages("DT")
install.packages("shinyalert")
install.packages("httr")
install.packages("curl")
install.packages("RCurl")
install.packages("XML")
install.packages("RJSONIO")
install.packages("sqldf")
install.packages("igraph")
install.packages("methods")
install.packages("xml2")
install.packages("png")
install.packages("fs")
install.packages("zoom")
install.packages("htmlwidgets")
install.packages("jsonlite")
install.packages("R.utils")
install.packages("igraph")
install.packages("shinycustomloader")
install.packages("shinydashboard")
install.packages("shinyBS")
install.packages("data.table")
install.packages("ps")
install.packages("webshot")
install.packages("shinyFeedback")
install.packages("rintrojs")
install.packages('remotes')
install.packages("rmarkdown")

#Gitlab packages ----
remotes::install_gitlab('CarlBrunius/MUVR')

#Github packages ----
devtools::install_github('cytoscape/cyjShiny')
devtools::install_github('mrjoh3/cytoscape')
devtools::install_github('stla/shinyCheckboxTree')
detach("package:InterMineR", unload = TRUE)
devtools::install_github('intermine/InterMineR')

#Bioconductor packages ----
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Biostrings")
BiocManager::install("RCyjs")
BiocManager::install("RCy3")
BiocManager::install("graph")
BiocManager::install("S4Vectors")
BiocManager::install("mixOmics")
